# Generated by Django 4.0.1 on 2023-08-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('vendor', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
